import Head from 'next/head'
 

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>google Clone App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='text-blue-800 bg-green-200 text-6xl font-bold text-center'>Testing</h1>
    </div>
  )
}
